In [16]:
!pip install tensorflow --quiet

In [4]:
import tensorflow as tf
print ("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.21188289,  0.41282597,  0.0800742 , -0.00762454,  0.20211409,
         0.6786971 ,  0.31276125, -0.6665114 ,  0.10731043,  0.12743461]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.10174511, 0.12438902, 0.08918048, 0.08169261, 0.10075603,
        0.16227381, 0.11254457, 0.04226996, 0.0916428 , 0.09350572]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.8184702

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 602us/step - loss: 0.2939 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 1s 554us/step - loss: 0.1397 - accuracy: 0.9589
Epoch 3/5
1875/1875 [==============================] - 1s 560us/step - loss: 0.1051 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 1s 563us/step - loss: 0.0851 - accuracy: 0.9741
Epoch 5/5
1875/1875 [==============================] - 1s 554us/step - loss: 0.0721 - accuracy: 0.9777


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0772 - accuracy: 0.9762 - 159ms/epoch - 509us/step


[0.07719089090824127, 0.9761999845504761]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.63820714e-08, 8.33675184e-10, 2.38912116e-06, 1.05199913e-04,
        9.42972003e-12, 3.51109264e-07, 1.41383744e-13, 9.99890208e-01,
        1.57697423e-06, 1.16074084e-07],
       [4.80029598e-07, 1.62736664e-03, 9.98322427e-01, 2.31142840e-05,
        1.11169408e-13, 3.16277671e-08, 3.91041262e-08, 1.82805038e-11,
        2.65197705e-05, 1.05448452e-12],
       [2.67907694e-07, 9.98883188e-01, 1.74609988e-04, 3.99070523e-05,
        1.70910753e-05, 9.16718363e-07, 2.59902504e-06, 3.77386401e-04,
        5.03319083e-04, 6.41388851e-07],
       [9.99533892e-01, 7.84289398e-07, 2.82455167e-05, 1.42840418e-06,
        1.97733480e-05, 1.59857009e-04, 2.06819052e-04, 3.96096329e-05,
        2.90056391e-06, 6.71506223e-06],
       [1.84491432e-06, 6.10978219e-08, 1.40228394e-05, 8.22275510e-08,
        9.95061338e-01, 3.69627924e-06, 3.25919086e-06, 1.83942611e-04,
        8.56111967e-07, 4.73077735e-03]], dtype=float32)>

URL: https://www.tensorflow.org/tutorials/quickstart/beginner